language: node_js
node_js:
  - lts/*
deploy:
  provider: npm
  email:
    secure: "EX1Xcv9csmoiBjQoZ32s6iQgCPaM3qSdET4Ni7NjzawA/KtYke3DQWkMMUyoNemyAN7RjnCzbUT+gmGD8TgXorbbc5VGw9IPD9M+qzwUL6ZrHg4oQtKN0xlvms6DaC0mzDE9lwlk1a/PNBrLm5bp1wYXoTelo0M91yIqu4wsgtdFJPP0XuCFZE4KpDVFWJaE/BSn/LG4aEh4AbwnMQKxUnaxqzWk8eLRBv1bkFAz9wvnh88KIjMqHgCjXf589snaaQVbPG7lFVHsgUEoPGTZePhVnNtXSTw8GMIdGmT8PfwGiVP9gyzgOYsk3uH6j6Us2B4iq6Zx1GoRRuOpS3t2uB0gHygbwNLW4eaXICTdpttozpw0XPxD92qj1iRNjJI4qyJRAbpsHrVulsD3F2ss6uACdZbm0sjDAS6Wcls5pUXZ52uuXgsjYJhgvZAOxceR/Kh/9cQY6XTA9YqEKVKvf3UOtUzKa/6xTC9BeA6FT+9qJcl/uMR0Z4UXRHaAXmjOHMUTG3saYFXFnyE/usAaEEFqxASk/d80PMW2CfL0x7JAdMGwn9P6r+gtwYL7w5ZFdPUmjnhWX1KZTTPCXSmX3T0YtORTfkuQ3iG/amZK+x9Ui9IWT02Jr2SQdsSxeiEgV0i+6Sasg4OhmSCnoSvoYaCBZzPC2wq7RTgHwuz5xNs="
  api_key: # a1e2
    secure: "RDknAIEd9UVTlGwYEZx478LbZyVz9WrYt33J9mhB5DJqTHDeH1ioY0LpE1udZhrJQwNk9yndLntXrNxip4nNwGUd6GKPMyR8tFcWdAnWMZWscgpB4jm/Rzv4zfPoThQN4v0yc5IXp41Lv2YiKfrA5I7XET1qkTA++CMrQYt/AfxSgQls2a8HaXqqnbmHYYTFWHmRxhZlaHG6thif4lxGXq4qjY20RMNsph16W5fuK5S+AeqYiOAgYfSPYr3GX7Xv78axFf168ET29rs5pVEygTPQGA6MlSwJtII9tzzyUAdGNgefVAT6+5eAxE7WYJKTRnd2X06I+7pYPF68RRUeCt5XpFV9tgNaE2Hmba9uf3Dew6NmgdnHNgJi0bzntuBP5u5If7gNG3GmB84LrsWSjMnhyxDDvpy4QaEdvYChCuKXNpFFZvgclo6UCHqfdf9lDg5d90CkcB9k7KbLmoeKb7W5371Oj9pxqlO6GdeXxhxhZKOdpmUY4PYVohJVpQ8rQ/A16OFBEJ3acZKSudLczEKqlD3fSsJ2UuDElg5nM2DntgguHpqmUAxNw/fsVaaMfTWdUggLpna2ZOQOH94PtelPYOl3qZxL2MmdOZKlGBMBbjCDwDFaWllURFQR4AcKlJA/ZS68XvgQcgU8IjEWzjdfGPMWOc6inV8pv7LzkJs="
  on:
    tags: true
    node: lts/*
